/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DiscardHalfWindow.java
 *
 * Created on Oct 17, 2013, 1:06:56 AM
 */
package settlerstrailstorails;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.imageio.ImageIO;

/**
 *
 * @author User 1
 */
public class DiscardHalfWindow extends javax.swing.JFrame {
    
    AveryJButton lumberButton,coalButton,cattleButton,oreButton,wheatButton;
    int discardNum;
    Player p;
    ArrayList<Player> discardPlayers;
    gameFrame game_Frame;

    /** Creates new form DiscardHalfWindow */
    DiscardHalfWindow(Player p, int num, ArrayList<Player> discardPlayers,gameFrame g) {
        initComponents();
        game_Frame=g;
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.discardPlayers=discardPlayers;
        this.setLocation(((dim.width/2)-(this.getSize().width/2)), ((dim.height/2)-((this.getSize().height/2)+20)));
        try{
            setIconImage(ImageIO.read(getClass().getResource("/settlerstrailstorails/resources/icon.png")));
        }catch(Exception e){
            
        }
        discardNum=num;
        this.p=p;
        coalButton = new AveryJButton(coalButton1);
        lumberButton = new AveryJButton(lumberButton1);
        cattleButton = new AveryJButton(cattleButton1);
        oreButton = new AveryJButton(oreButton1);
        wheatButton = new AveryJButton(wheatButton1);
        if(p.getLumber()<1){
            lumberButton.setVisible(false);
        }
        if(p.getCoal()<1){
            coalButton.setVisible(false);
        }
        if(p.getCattle()<1){
            cattleButton.setVisible(false);
        }
        if(p.getOre()<1){
            oreButton.setVisible(false);
        }
        if(p.getWheat()<1){
            wheatButton.setVisible(false);
        }
        jLabel1.setText("You must discard "+num+" more resources");
    }
    public DiscardHalfWindow(){
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lumberButton1 = new javax.swing.JButton();
        coalButton1 = new javax.swing.JButton();
        cattleButton1 = new javax.swing.JButton();
        oreButton1 = new javax.swing.JButton();
        wheatButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setAlwaysOnTop(true);
        setFocusable(false);
        setFocusableWindowState(false);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lumberButton1.setBackground(new java.awt.Color(239, 228, 176));
        lumberButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        lumberButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/settlerstrailstorails/resources/lumberRaw.png"))); // NOI18N
        lumberButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lumberButton1.setContentAreaFilled(false);
        lumberButton1.setFocusable(false);
        lumberButton1.setOpaque(true);
        lumberButton1.setPreferredSize(new java.awt.Dimension(75, 25));
        lumberButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lumberButton1MouseReleased(evt);
            }
        });
        jPanel1.add(lumberButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 65, 50, 50));

        coalButton1.setBackground(new java.awt.Color(239, 228, 176));
        coalButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        coalButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/settlerstrailstorails/resources/coalRaw.png"))); // NOI18N
        coalButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        coalButton1.setContentAreaFilled(false);
        coalButton1.setFocusable(false);
        coalButton1.setOpaque(true);
        coalButton1.setPreferredSize(new java.awt.Dimension(75, 25));
        coalButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                coalButton1MouseReleased(evt);
            }
        });
        jPanel1.add(coalButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 65, 50, 50));

        cattleButton1.setBackground(new java.awt.Color(239, 228, 176));
        cattleButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12));
        cattleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/settlerstrailstorails/resources/cattleRaw.png"))); // NOI18N
        cattleButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cattleButton1.setContentAreaFilled(false);
        cattleButton1.setFocusable(false);
        cattleButton1.setOpaque(true);
        cattleButton1.setPreferredSize(new java.awt.Dimension(75, 25));
        cattleButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cattleButton1MouseReleased(evt);
            }
        });
        jPanel1.add(cattleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 65, 50, 50));

        oreButton1.setBackground(new java.awt.Color(239, 228, 176));
        oreButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        oreButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/settlerstrailstorails/resources/oreRaw.png"))); // NOI18N
        oreButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        oreButton1.setContentAreaFilled(false);
        oreButton1.setFocusable(false);
        oreButton1.setOpaque(true);
        oreButton1.setPreferredSize(new java.awt.Dimension(75, 25));
        oreButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                oreButton1MouseReleased(evt);
            }
        });
        jPanel1.add(oreButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 65, 50, 50));

        wheatButton1.setBackground(new java.awt.Color(239, 228, 176));
        wheatButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12));
        wheatButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/settlerstrailstorails/resources/wheatRaw.png"))); // NOI18N
        wheatButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        wheatButton1.setContentAreaFilled(false);
        wheatButton1.setFocusable(false);
        wheatButton1.setOpaque(true);
        wheatButton1.setPreferredSize(new java.awt.Dimension(75, 25));
        wheatButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                wheatButton1MouseReleased(evt);
            }
        });
        jPanel1.add(wheatButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 65, 50, 50));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("You must discard 0 more resources");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 360, -1));

        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/settlerstrailstorails/resources/mineralRightsBackground.png"))); // NOI18N
        jPanel1.add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 140));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void lumberButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lumberButton1MouseReleased
        if (lumberButton.isAble()) {
            discardNum--;
            p.minusLumber();
            jLabel1.setText("You must discard " + discardNum + " more resources");
            if (p.getLumber() < 1) {
                lumberButton.setVisible(false);
            }
            if(discardNum==0){
                if(!discardPlayers.isEmpty()){
                    Player p2 = discardPlayers.remove(0);
                    p2.setTurn(true);
                    game_Frame.setCurrPlayer(p2);
                    game_Frame.setBackgroundPlayer();
                    p2.discardHalf(discardPlayers,game_Frame);
                }else{
                    game_Frame.setCurrPlayer(game_Frame.getRealPlayer());
                    game_Frame.resetRealPlayer();
                    game_Frame.getCurrPlayer().setTurn(true);
                    game_Frame.setDisableCityButton(false);
                    game_Frame.setBackgroundPlayer();
                    game_Frame.moveRobber();
                }
                this.setVisible(false);   
            }
        }
}//GEN-LAST:event_lumberButton1MouseReleased
    private void coalButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coalButton1MouseReleased
        if(coalButton.isAble()) {
            discardNum--;
            p.minusCoal();
            jLabel1.setText("You must discard " + discardNum + " more resources");
            if (p.getCoal() < 1) {
                coalButton.setVisible(false);
            }
            if(discardNum==0){
                if(!discardPlayers.isEmpty()){
                    Player p2 = discardPlayers.remove(0);
                    p2.setTurn(true);
                    game_Frame.setCurrPlayer(p2);
                    game_Frame.setBackgroundPlayer();
                    p2.discardHalf(discardPlayers,game_Frame);
                }else{
                    game_Frame.setCurrPlayer(game_Frame.getRealPlayer());
                    game_Frame.resetRealPlayer();
                    game_Frame.getCurrPlayer().setTurn(true);
                    game_Frame.setDisableCityButton(false);
                    game_Frame.setBackgroundPlayer();
                    game_Frame.moveRobber();
                }
                this.setVisible(false);            
            }
        }
}//GEN-LAST:event_coalButton1MouseReleased
    private void cattleButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cattleButton1MouseReleased
        if(cattleButton.isAble()){
            discardNum--;
            p.minusCattle();
            jLabel1.setText("You must discard " + discardNum + " more resources");
            if (p.getCattle() < 1) {
                cattleButton.setVisible(false);
            }
            if(discardNum==0){
                if(!discardPlayers.isEmpty()){
                    Player p2 = discardPlayers.remove(0);
                    p2.setTurn(true);
                    game_Frame.setCurrPlayer(p2);
                    game_Frame.setBackgroundPlayer();
                    p2.discardHalf(discardPlayers,game_Frame);
                }else{
                    game_Frame.setCurrPlayer(game_Frame.getRealPlayer());
                    game_Frame.resetRealPlayer();
                    game_Frame.getCurrPlayer().setTurn(true);
                    game_Frame.setDisableCityButton(false);
                    game_Frame.setBackgroundPlayer();
                    game_Frame.moveRobber();
                }
                this.setVisible(false);   
            }
        }
}//GEN-LAST:event_cattleButton1MouseReleased
    private void oreButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oreButton1MouseReleased
        if(oreButton.isAble()){
            discardNum--;
            p.minusOre();
            jLabel1.setText("You must discard " + discardNum + " more resources");
            if (p.getOre() < 1) {
                oreButton.setVisible(false);
            }
            if(discardNum==0){
                if(!discardPlayers.isEmpty()){
                    Player p2 = discardPlayers.remove(0);
                    p2.setTurn(true);
                    game_Frame.setCurrPlayer(p2);
                    game_Frame.setBackgroundPlayer();
                    p2.discardHalf(discardPlayers,game_Frame);
                }else{
                    game_Frame.setCurrPlayer(game_Frame.getRealPlayer());
                    game_Frame.resetRealPlayer();
                    game_Frame.getCurrPlayer().setTurn(true);
                    game_Frame.setDisableCityButton(false);
                    game_Frame.setBackgroundPlayer();
                    game_Frame.moveRobber();
                }
                this.setVisible(false);   
            }
        }
}//GEN-LAST:event_oreButton1MouseReleased
    private void wheatButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wheatButton1MouseReleased
        if(wheatButton.isAble()){
            discardNum--;
            p.minusWheat();
            jLabel1.setText("You must discard " + discardNum + " more resources");
            if (p.getWheat() < 1) {
                wheatButton.setVisible(false);
            }
            if(discardNum==0){
                if(!discardPlayers.isEmpty()){
                    Player p2 = discardPlayers.remove(0);
                    p2.setTurn(true);
                    game_Frame.setCurrPlayer(p2);
                    game_Frame.setBackgroundPlayer();
                    p2.discardHalf(discardPlayers,game_Frame);
                }else{                    
                    game_Frame.setCurrPlayer(game_Frame.getRealPlayer());
                    game_Frame.resetRealPlayer();
                    game_Frame.getCurrPlayer().setTurn(true);
                    game_Frame.setDisableCityButton(false);
                    game_Frame.setBackgroundPlayer();
                    game_Frame.moveRobber();
                }
                this.setVisible(false);
            }
        }
}//GEN-LAST:event_wheatButton1MouseReleased
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new DiscardHalfWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JButton cattleButton1;
    private javax.swing.JButton coalButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton lumberButton1;
    private javax.swing.JButton oreButton1;
    private javax.swing.JButton wheatButton1;
    // End of variables declaration//GEN-END:variables
}
