/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * moreMessagesWindow.java
 *
 * Created on Sep 30, 2013, 1:01:12 PM
 */
package settlerstrailstorails;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.border.BevelBorder;

/**
 *
 * @author User 1
 */
public class moreMessagesWindow extends javax.swing.JFrame {
    
    boolean buttonPressed=false, mouseOnOkayButton=false;
    String[] messages;

    /** Creates new form moreMessagesWindow */
    public moreMessagesWindow() {
        initComponents();
    }
    public moreMessagesWindow(ArrayList<String> m) {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        try{
            setIconImage(ImageIO.read(getClass().getResource("/settlerstrailstorails/resources/icon.png")));
        }catch(Exception e){
            
        }
        this.messages=new String[m.size()];
        for(int i=0;i<messages.length;i++){
            messages[i]=m.get(i);
        }
        messageList.setListData(messages);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        messageList = new javax.swing.JList();
        okayButton = new javax.swing.JButton();
        backgroundLabel = new javax.swing.JLabel();

        setFocusable(false);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setEnabled(false);

        jScrollPane1.setViewportView(messageList);

        mainPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 301, 430));

        okayButton.setBackground(new java.awt.Color(239, 228, 176));
        okayButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14));
        okayButton.setText("OK");
        okayButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        okayButton.setContentAreaFilled(false);
        okayButton.setFocusable(false);
        okayButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        okayButton.setMaximumSize(new java.awt.Dimension(50, 50));
        okayButton.setMinimumSize(new java.awt.Dimension(40, 40));
        okayButton.setPreferredSize(new java.awt.Dimension(40, 40));
        okayButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                okayButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                okayButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                okayButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                okayButtonMouseReleased(evt);
            }
        });
        okayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okayButtonActionPerformed(evt);
            }
        });
        mainPanel.add(okayButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, 100, 30));

        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/settlerstrailstorails/resources/MainMenuBackground.png"))); // NOI18N
        mainPanel.add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okayButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okayButtonMouseEntered
        mouseOnOkayButton=true;
}//GEN-LAST:event_okayButtonMouseEntered
    private void okayButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okayButtonMouseExited
        if(mouseOnOkayButton&&buttonPressed){
            okayButton.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));
            okayButton.setLocation(okayButton.getX() + 1, okayButton.getY());
        }
        mouseOnOkayButton=false;
        buttonPressed=false;
}//GEN-LAST:event_okayButtonMouseExited
    private void okayButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okayButtonMousePressed
        gameFrame.playSound("click");
        okayButton.setBorder(BorderFactory.createBevelBorder(BevelBorder.LOWERED));
        okayButton.setLocation(okayButton.getX()-1, okayButton.getY());
        buttonPressed=true;
}//GEN-LAST:event_okayButtonMousePressed
    private void okayButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okayButtonMouseReleased
        buttonPressed=false;
        if(mouseOnOkayButton) {
            okayButton.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));
            okayButton.setLocation(okayButton.getX() + 1, okayButton.getY());
            this.setVisible(false);
        }
}//GEN-LAST:event_okayButtonMouseReleased
    private void okayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okayButtonActionPerformed
        
}//GEN-LAST:event_okayButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new moreMessagesWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JList messageList;
    private javax.swing.JButton okayButton;
    // End of variables declaration//GEN-END:variables
}
