/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NativeSupportWindow.java
 *
 * Created on Oct 16, 2013, 12:16:37 AM
 */
package settlerstrailstorails;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.imageio.ImageIO;

/**
 *
 * @author User 1
 */
public class NativeSupportWindow extends javax.swing.JFrame {
    
    AveryJButton twoButton,threeButton,fourButton,fiveButton,sixButton,
            sevenButton,eightButton,nineButton,tenButton,elevenButton,
            twelveButton;
    gameFrame game_Frame;

    /** Creates new form NativeSupportWindow */
    NativeSupportWindow(gameFrame g) {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(((dim.width/2)-(this.getSize().width/2)), ((dim.height/2)-((this.getSize().height/2)+20)));
        try{
            setIconImage(ImageIO.read(getClass().getResource("/settlerstrailstorails/resources/icon.png")));
        }catch(Exception e){
            
        }
        game_Frame=g;
        twoButton=new AveryJButton(twoButton1);
        threeButton=new AveryJButton(threeButton1);
        fourButton=new AveryJButton(fourButton1);
        fiveButton=new AveryJButton(fiveButton1);
        sixButton=new AveryJButton(sixButton1);
        sevenButton=new AveryJButton(sevenButton1);
        eightButton=new AveryJButton(eightButton1);
        nineButton=new AveryJButton(nineButton1);
        tenButton=new AveryJButton(tenButton1);
        elevenButton=new AveryJButton(elevenButton1);
        twelveButton=new AveryJButton(twelveButton1);
    }
    NativeSupportWindow(){
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        twoButton1 = new javax.swing.JButton();
        eightButton1 = new javax.swing.JButton();
        sixButton1 = new javax.swing.JButton();
        twelveButton1 = new javax.swing.JButton();
        threeButton1 = new javax.swing.JButton();
        nineButton1 = new javax.swing.JButton();
        fiveButton1 = new javax.swing.JButton();
        elevenButton1 = new javax.swing.JButton();
        fourButton1 = new javax.swing.JButton();
        tenButton1 = new javax.swing.JButton();
        sevenButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        twoButton1.setBackground(new java.awt.Color(239, 228, 176));
        twoButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18));
        twoButton1.setText("2");
        twoButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        twoButton1.setContentAreaFilled(false);
        twoButton1.setFocusable(false);
        twoButton1.setOpaque(true);
        twoButton1.setPreferredSize(new java.awt.Dimension(75, 25));
        twoButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                twoButton1MouseReleased(evt);
            }
        });
        jPanel1.add(twoButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 39, 38, 38));

        eightButton1.setBackground(new java.awt.Color(239, 228, 176));
        eightButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18));
        eightButton1.setText("8");
        eightButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        eightButton1.setContentAreaFilled(false);
        eightButton1.setFocusable(false);
        eightButton1.setOpaque(true);
        eightButton1.setPreferredSize(new java.awt.Dimension(75, 25));
        eightButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                eightButton1MouseReleased(evt);
            }
        });
        jPanel1.add(eightButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 86, 38, 38));

        sixButton1.setBackground(new java.awt.Color(239, 228, 176));
        sixButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18));
        sixButton1.setText("6");
        sixButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sixButton1.setContentAreaFilled(false);
        sixButton1.setFocusable(false);
        sixButton1.setOpaque(true);
        sixButton1.setPreferredSize(new java.awt.Dimension(75, 25));
        sixButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                sixButton1MouseReleased(evt);
            }
        });
        jPanel1.add(sixButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 39, 38, 38));

        twelveButton1.setBackground(new java.awt.Color(239, 228, 176));
        twelveButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18));
        twelveButton1.setText("12");
        twelveButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        twelveButton1.setContentAreaFilled(false);
        twelveButton1.setFocusable(false);
        twelveButton1.setOpaque(true);
        twelveButton1.setPreferredSize(new java.awt.Dimension(75, 25));
        twelveButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                twelveButton1MouseReleased(evt);
            }
        });
        jPanel1.add(twelveButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 86, 38, 38));

        threeButton1.setBackground(new java.awt.Color(239, 228, 176));
        threeButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18));
        threeButton1.setText("3");
        threeButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        threeButton1.setContentAreaFilled(false);
        threeButton1.setFocusable(false);
        threeButton1.setOpaque(true);
        threeButton1.setPreferredSize(new java.awt.Dimension(75, 25));
        threeButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                threeButton1MouseReleased(evt);
            }
        });
        jPanel1.add(threeButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 39, 38, 38));

        nineButton1.setBackground(new java.awt.Color(239, 228, 176));
        nineButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18));
        nineButton1.setText("9");
        nineButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nineButton1.setContentAreaFilled(false);
        nineButton1.setFocusable(false);
        nineButton1.setOpaque(true);
        nineButton1.setPreferredSize(new java.awt.Dimension(75, 25));
        nineButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                nineButton1MouseReleased(evt);
            }
        });
        jPanel1.add(nineButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 86, 38, 38));

        fiveButton1.setBackground(new java.awt.Color(239, 228, 176));
        fiveButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18));
        fiveButton1.setText("5");
        fiveButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fiveButton1.setContentAreaFilled(false);
        fiveButton1.setFocusable(false);
        fiveButton1.setOpaque(true);
        fiveButton1.setPreferredSize(new java.awt.Dimension(75, 25));
        fiveButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                fiveButton1MouseReleased(evt);
            }
        });
        jPanel1.add(fiveButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 39, 38, 38));

        elevenButton1.setBackground(new java.awt.Color(239, 228, 176));
        elevenButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18));
        elevenButton1.setText("11");
        elevenButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        elevenButton1.setContentAreaFilled(false);
        elevenButton1.setFocusable(false);
        elevenButton1.setOpaque(true);
        elevenButton1.setPreferredSize(new java.awt.Dimension(75, 25));
        elevenButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                elevenButton1MouseReleased(evt);
            }
        });
        jPanel1.add(elevenButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 86, 38, 38));

        fourButton1.setBackground(new java.awt.Color(239, 228, 176));
        fourButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18));
        fourButton1.setText("4");
        fourButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fourButton1.setContentAreaFilled(false);
        fourButton1.setFocusable(false);
        fourButton1.setOpaque(true);
        fourButton1.setPreferredSize(new java.awt.Dimension(75, 25));
        fourButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                fourButton1MouseReleased(evt);
            }
        });
        jPanel1.add(fourButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 39, 38, 38));

        tenButton1.setBackground(new java.awt.Color(239, 228, 176));
        tenButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18));
        tenButton1.setText("10");
        tenButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tenButton1.setContentAreaFilled(false);
        tenButton1.setFocusable(false);
        tenButton1.setOpaque(true);
        tenButton1.setPreferredSize(new java.awt.Dimension(75, 25));
        tenButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tenButton1MouseReleased(evt);
            }
        });
        jPanel1.add(tenButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 86, 38, 38));

        sevenButton1.setBackground(new java.awt.Color(239, 228, 176));
        sevenButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18));
        sevenButton1.setText("7");
        sevenButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sevenButton1.setContentAreaFilled(false);
        sevenButton1.setFocusable(false);
        sevenButton1.setOpaque(true);
        sevenButton1.setPreferredSize(new java.awt.Dimension(75, 25));
        sevenButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                sevenButton1MouseReleased(evt);
            }
        });
        jPanel1.add(sevenButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 39, 38, 85));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Select the dice roll you'd like.");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, 360, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/settlerstrailstorails/resources/mineralRightsBackground.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 140));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void twoButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_twoButton1MouseReleased
        if(twoButton.isAble()) {
            gameFrame.addToInfo(game_Frame.getCurrPlayer().getName() + " rolled a 2.", false);
            game_Frame.getResources(2);
            game_Frame.rollToBuild();
            game_Frame.enableMenu();
            this.setVisible(false);
            game_Frame.enableMenu();
        }
}//GEN-LAST:event_twoButton1MouseReleased
    private void eightButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eightButton1MouseReleased
        if(eightButton.isAble()) {
            gameFrame.addToInfo(game_Frame.getCurrPlayer().getName() + " rolled a 8.", false);
            game_Frame.getResources(8);
            game_Frame.rollToBuild();
            game_Frame.enableMenu();
            this.setVisible(false);
            game_Frame.enableMenu();
        }
    }//GEN-LAST:event_eightButton1MouseReleased
    private void sixButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sixButton1MouseReleased
        if(sixButton.isAble()) {
            gameFrame.addToInfo(game_Frame.getCurrPlayer().getName() + " rolled a 6.", false);
            game_Frame.getResources(6);
            game_Frame.rollToBuild();
            game_Frame.enableMenu();
            this.setVisible(false);
            game_Frame.enableMenu();
        }
    }//GEN-LAST:event_sixButton1MouseReleased
    private void twelveButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_twelveButton1MouseReleased
        if(twelveButton.isAble()) {
            gameFrame.addToInfo(game_Frame.getCurrPlayer().getName() + " rolled a 12.", false);
            game_Frame.getResources(12);
            game_Frame.rollToBuild();
            game_Frame.enableMenu();
            this.setVisible(false);
            game_Frame.enableMenu();
        }
    }//GEN-LAST:event_twelveButton1MouseReleased
    private void threeButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_threeButton1MouseReleased
        if(threeButton.isAble()) {
            gameFrame.addToInfo(game_Frame.getCurrPlayer().getName() + " rolled a 3.", false);
            game_Frame.getResources(3);
            game_Frame.rollToBuild();
            game_Frame.enableMenu();
            this.setVisible(false);
            game_Frame.enableMenu();
        }
    }//GEN-LAST:event_threeButton1MouseReleased
    private void nineButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nineButton1MouseReleased
        if(nineButton.isAble()) {
            gameFrame.addToInfo(game_Frame.getCurrPlayer().getName() + " rolled a 9.", false);
            game_Frame.getResources(9);
            game_Frame.rollToBuild();
            game_Frame.enableMenu();
            this.setVisible(false);
            game_Frame.enableMenu();
        }
    }//GEN-LAST:event_nineButton1MouseReleased
    private void fiveButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fiveButton1MouseReleased
        if(fiveButton.isAble()) {
            gameFrame.addToInfo(game_Frame.getCurrPlayer().getName() + " rolled a 5.", false);
            game_Frame.getResources(5);
            game_Frame.rollToBuild();
            game_Frame.enableMenu();
            this.setVisible(false);
            game_Frame.enableMenu();
        }
    }//GEN-LAST:event_fiveButton1MouseReleased
    private void elevenButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elevenButton1MouseReleased
        if(elevenButton.isAble()) {
            gameFrame.addToInfo(game_Frame.getCurrPlayer().getName() + " rolled a 11.", false);
            game_Frame.getResources(11);
            game_Frame.rollToBuild();
            game_Frame.enableMenu();
            this.setVisible(false);
            game_Frame.enableMenu();
        }
    }//GEN-LAST:event_elevenButton1MouseReleased
    private void fourButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fourButton1MouseReleased
        if(fourButton.isAble()) {
            gameFrame.addToInfo(game_Frame.getCurrPlayer().getName() + " rolled a 4.", false);
            game_Frame.getResources(4);
            game_Frame.rollToBuild();
            game_Frame.enableMenu();
            this.setVisible(false);
            game_Frame.enableMenu();
        }
    }//GEN-LAST:event_fourButton1MouseReleased
    private void tenButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tenButton1MouseReleased
        if(tenButton.isAble()) {
            gameFrame.addToInfo(game_Frame.getCurrPlayer().getName() + " rolled a 10.", false);
            game_Frame.getResources(10);
            game_Frame.rollToBuild();
            game_Frame.enableMenu();
            this.setVisible(false);
            game_Frame.enableMenu();
        }
    }//GEN-LAST:event_tenButton1MouseReleased
    private void sevenButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sevenButton1MouseReleased
        if(sevenButton.isAble()) {
            gameFrame.addToInfo(game_Frame.getCurrPlayer().getName() + " rolled a 7.", false);
            game_Frame.rollSeven();
            game_Frame.rollToBuild();
            game_Frame.enableMenu();
            this.setVisible(false);
            game_Frame.enableMenu();
        }
    }//GEN-LAST:event_sevenButton1MouseReleased
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new NativeSupportWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton eightButton1;
    private javax.swing.JButton elevenButton1;
    private javax.swing.JButton fiveButton1;
    private javax.swing.JButton fourButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton nineButton1;
    private javax.swing.JButton sevenButton1;
    private javax.swing.JButton sixButton1;
    private javax.swing.JButton tenButton1;
    private javax.swing.JButton threeButton1;
    private javax.swing.JButton twelveButton1;
    private javax.swing.JButton twoButton1;
    // End of variables declaration//GEN-END:variables
}
